export interface Account {
  id: string;
  name: string;
  stage: "Lead" | "Opportunity" | "Customer";
  activity: number[];
  website: string;
  location: string;
  employeeRange: string;
  categories: string[];
  logo: string; // Add this new field
}

export const accounts: Account[] = [
  {
    id: "1",
    name: "Notion",
    stage: "Customer",
    activity: [5, 8, 12, 7, 9, 11, 13, 15, 14, 12, 10, 9],
    website: "notion.so",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Productivity", "SaaS", "Collaboration"],
    logo: "https://www.notion.com/front-static/favicon.ico",
  },
  {
    id: "2",
    name: "Stripe",
    stage: "Customer",
    activity: [8, 10, 9, 11, 13, 14, 15, 16, 17, 18, 19, 20],
    website: "stripe.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Payments", "FinTech", "Enterprise"],
    logo: "https://stripe.com/favicon.ico",
  },
  {
    id: "3",
    name: "Slack",
    stage: "Customer",
    activity: [10, 12, 14, 12, 10, 8, 9, 11, 13, 15, 14, 16],
    website: "slack.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Communication", "Enterprise", "SaaS"],
    logo: "https://slack.com/favicon.ico",
  },
  {
    id: "4",
    name: "Figma",
    stage: "Opportunity",
    activity: [3, 5, 7, 9, 8, 10, 12, 14, 13, 15, 17, 16],
    website: "figma.com",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Design", "Collaboration", "SaaS"],
    logo: "https://static.figma.com/app/icon/1/favicon.png",
  },
  {
    id: "5",
    name: "Shopify",
    stage: "Lead",
    activity: [2, 3, 2, 4, 3, 5, 4, 6, 5, 7, 6, 8],
    website: "shopify.com",
    location: "Ottawa, Canada",
    employeeRange: "5k+",
    categories: ["B2B", "E-commerce", "Enterprise", "SaaS"],
    logo: "https://www.shopify.com/favicon.ico",
  },
  {
    id: "6",
    name: "Airtable",
    stage: "Opportunity",
    activity: [4, 6, 8, 7, 9, 11, 10, 12, 14, 13, 15, 14],
    website: "airtable.com",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Productivity", "Database", "SaaS"],
    logo: "https://airtable.com/favicon.ico",
  },
  {
    id: "7",
    name: "Atlassian",
    stage: "Customer",
    activity: [15, 14, 16, 18, 17, 19, 20, 19, 21, 20, 22, 21],
    website: "atlassian.com",
    location: "Sydney, Australia",
    employeeRange: "5k+",
    categories: ["B2B", "Enterprise", "Productivity", "Collaboration"],
    logo: "https://www.atlassian.com/favicon.ico",
  },
  {
    id: "8",
    name: "Canva",
    stage: "Lead",
    activity: [1, 2, 3, 4, 3, 5, 4, 6, 5, 7, 6, 5],
    website: "canva.com",
    location: "Sydney, Australia",
    employeeRange: "1k-5k",
    categories: ["B2B", "Design", "SaaS", "Productivity"],
    logo: "https://www.canva.com/favicon.ico",
  },
  {
    id: "9",
    name: "Twilio",
    stage: "Opportunity",
    activity: [5, 7, 6, 8, 7, 9, 8, 10, 9, 11, 10, 12],
    website: "twilio.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Communication", "API", "Enterprise"],
    logo: "https://www.twilio.com/favicon.ico",
  },
  {
    id: "10",
    name: "Asana",
    stage: "Lead",
    activity: [2, 4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9],
    website: "asana.com",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Productivity", "Project Management", "SaaS"],
    logo: "https://asana.com/favicon.ico",
  },
  {
    id: "11",
    name: "Zendesk",
    stage: "Customer",
    activity: [12, 14, 13, 15, 14, 16, 15, 17, 16, 18, 17, 19],
    website: "zendesk.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Customer Support", "Enterprise", "SaaS"],
    logo: "https://www.zendesk.com/favicon.ico",
  },
  {
    id: "12",
    name: "HubSpot",
    stage: "Opportunity",
    activity: [6, 8, 7, 9, 8, 10, 9, 11, 10, 12, 11, 13],
    website: "hubspot.com",
    location: "Cambridge, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Marketing", "CRM", "Enterprise"],
    logo: "https://www.hubspot.com/hubfs/HubSpot_Logos/HubSpot-Inversed-Favicon.png",
  },
  {
    id: "13",
    name: "Notion",
    stage: "Customer",
    activity: [5, 8, 12, 7, 9, 11, 13, 15, 14, 12, 10, 9],
    website: "notion.so",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Productivity", "SaaS", "Collaboration"],
    logo: "https://www.notion.com/front-static/favicon.ico",
  },
  {
    id: "14",
    name: "Stripe",
    stage: "Customer",
    activity: [8, 10, 9, 11, 13, 14, 15, 16, 17, 18, 19, 20],
    website: "stripe.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Payments", "FinTech", "Enterprise"],
    logo: "https://stripe.com/favicon.ico",
  },
  {
    id: "15",
    name: "Slack",
    stage: "Customer",
    activity: [10, 12, 14, 12, 10, 8, 9, 11, 13, 15, 14, 16],
    website: "slack.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Communication", "Enterprise", "SaaS"],
    logo: "https://slack.com/favicon.ico",
  },
  {
    id: "16",
    name: "Figma",
    stage: "Opportunity",
    activity: [3, 5, 7, 9, 8, 10, 12, 14, 13, 15, 17, 16],
    website: "figma.com",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Design", "Collaboration", "SaaS"],
    logo: "https://static.figma.com/app/icon/1/favicon.png",
  },
  {
    id: "17",
    name: "Shopify",
    stage: "Lead",
    activity: [2, 3, 2, 4, 3, 5, 4, 6, 5, 7, 6, 8],
    website: "shopify.com",
    location: "Ottawa, Canada",
    employeeRange: "5k+",
    categories: ["B2B", "E-commerce", "Enterprise", "SaaS"],
    logo: "https://www.shopify.com/favicon.ico",
  },
  {
    id: "18",
    name: "Airtable",
    stage: "Opportunity",
    activity: [4, 6, 8, 7, 9, 11, 10, 12, 14, 13, 15, 14],
    website: "airtable.com",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Productivity", "Database", "SaaS"],
    logo: "https://airtable.com/favicon.ico",
  },
  {
    id: "19",
    name: "Atlassian",
    stage: "Customer",
    activity: [15, 14, 16, 18, 17, 19, 20, 19, 21, 20, 22, 21],
    website: "atlassian.com",
    location: "Sydney, Australia",
    employeeRange: "5k+",
    categories: ["B2B", "Enterprise", "Productivity", "Collaboration"],
    logo: "https://www.atlassian.com/favicon.ico",
  },
  {
    id: "20",
    name: "Canva",
    stage: "Lead",
    activity: [1, 2, 3, 4, 3, 5, 4, 6, 5, 7, 6, 5],
    website: "canva.com",
    location: "Sydney, Australia",
    employeeRange: "1k-5k",
    categories: ["B2B", "Design", "SaaS", "Productivity"],
    logo: "https://www.canva.com/favicon.ico",
  },
  {
    id: "21",
    name: "Twilio",
    stage: "Opportunity",
    activity: [5, 7, 6, 8, 7, 9, 8, 10, 9, 11, 10, 12],
    website: "twilio.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Communication", "API", "Enterprise"],
    logo: "https://www.twilio.com/favicon.ico",
  },
  {
    id: "22",
    name: "Asana",
    stage: "Lead",
    activity: [2, 4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9],
    website: "asana.com",
    location: "San Francisco, USA",
    employeeRange: "251-1k",
    categories: ["B2B", "Productivity", "Project Management", "SaaS"],
    logo: "https://asana.com/favicon.ico",
  },
  {
    id: "23",
    name: "Zendesk",
    stage: "Customer",
    activity: [12, 14, 13, 15, 14, 16, 15, 17, 16, 18, 17, 19],
    website: "zendesk.com",
    location: "San Francisco, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Customer Support", "Enterprise", "SaaS"],
    logo: "https://www.zendesk.com/favicon.ico",
  },
  {
    id: "24",
    name: "HubSpot",
    stage: "Opportunity",
    activity: [6, 8, 7, 9, 8, 10, 9, 11, 10, 12, 11, 13],
    website: "hubspot.com",
    location: "Cambridge, USA",
    employeeRange: "1k-5k",
    categories: ["B2B", "Marketing", "CRM", "Enterprise"],
    logo: "https://www.hubspot.com/hubfs/HubSpot_Logos/HubSpot-Inversed-Favicon.png",
  },
];
